- name: Variables Demo
  hosts: localhost
  vars:
    URL: play.example.com
    STRING: Hello
    NUMBER1: 1
    NUMBER2: 3.2
    BOOLEAN1: true
    BOOLEAN2: false
    BOOLEAN3: yes
    BOOLEAN4: no
  vars_files:
    - vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

    - name: Print Fruit Name
      ansible.builtin.debug:
        msg: Fruit - {{ FRUIT }}
      vars:
        FRUIT: apple

    - name: Print Project Name
      ansible.builtin.debug:
        msg: PROJECT_NAME - {{ PROJECT_NAME }}

    - name: Print CLI Variable
      ansible.builtin.debug:
        msg: COURSE NAME - {{ COURSE_NAME }}

    - name: List variable
      ansible.builtin.debug:
        msg: First Fruit Name - {{ FRUITS[0] }}, Second Fruit Name - {{ FRUITS[1] }}
      vars:
        FRUITS:
          - banana
          - apple

    - name: Map variable
      ansible.builtin.debug:
        msg: Course Name - {{ COURSE["name"] }} , Trainer Name - {{ COURSE["trainer"] }}
      vars:
        COURSE:
          name: DevOps
          trainer: John

# You can access a variable with out quotes, However if the value is starting with variable then use double/single quotes
# Variable not stating with value  Ex: msg: URL - {{ URL }}
# Variable stating with value  Ex: msg: "{{ URL }}", In this case we need to quote it.

    - name: Execute shell command
      ansible.builtin.shell: uptime
      register: OUT

    - name: Print OUT
      ansible.builtin.debug:
        msg: "{{OUT}}"








