- name: Variables Demo
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

    - name: Print Fruit Name
      ansible.builtin.debug:
        msg: Fruit - {{ FRUIT }}
      vars:
        FRUIT: apple


