- name: Conditions
  hosts: localhost
  tasks:
    - name: Welcome to DevOps Course
      ansible.builtin.debug:
        msg: Welcome to DevOps Course

    - name: Welcome to AWS Course
      ansible.builtin.debug:
        msg: Welcome to AWS Course


